### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/CapturePointClaims#1]
Protect posts from damage

- [ ] Store region ID with clan
- [ ] Set owning clan name on sign
- [ ] "unclaim" regions when clan disbands
- [ ] "create" claim field on capture
---
- [x] Use bossbar for capture progress
- [x] Notify all online clan members on point capture

**Comment by RoboMWM** [comment]
hmmm I did this all without ever looking at this issue ever again since checking those two boxes lol.
